services:
  pgsql:
    build:
      context: .
      dockerfile: PgSql.Dockerfile
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    ports:
      - 54321:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=users,deliveries
  user:
    build:
      context: users/
    ports:
      - 8080:8080
    depends_on:
      - pgsql
    restart: on-failure
    environment:
      - PG_HOST=pgsql
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DBNAME=users
      - JWT_SIGN_KEY=customKey
  deliveries:
    build:
      context: deliveries/
    ports:
      - 8081:8080
    depends_on:
      - pgsql
    restart: on-failure
    environment:
      - PG_HOST=pgsql
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DBNAME=deliveries
      - USERS_BASE_URL=http://user:8080
