services:
  pgsql:
    image: postgres:alpine
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    ports:
      - 54321:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  user:
    build:
      context: users/
    ports:
      - 8080:8080
    depends_on:
      - pgsql
    environment:
      - PG_HOST=pgsql
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DBNAME=postgres
      - JWT_SIGN_KEY=customKey
