basePath: /
definitions:
  dto.UserDto:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  entities.User:
    properties:
      email:
        type: string
      id:
        type: integer
      role:
        type: string
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: zhanbolat.nurutdin@gmail.com
    name: Zhanbolat
  title: Parcel Delivery Service
  version: "1.0"
paths:
  /auth:
    post:
      description: authorization on service with JWT token and return user info
      parameters:
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.User'
        "401":
          description: Unauthorized
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Authorization
  /courier:
    post:
      consumes:
      - application/json
      description: Create courier account on service with email and password. Only
        admin have permission.
      parameters:
      - description: courier info
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/dto.UserDto'
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.User'
        "400":
          description: Bad Request
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  type: string
              type: object
        "401":
          description: Unauthorized
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  type: string
              type: object
        "403":
          description: Forbidden
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  type: string
              type: object
      summary: Create courier account
  /login:
    post:
      consumes:
      - application/json
      description: authentication on service with email and password
      parameters:
      - description: login info
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/dto.UserDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - type: object
            - properties:
                token:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  type: string
              type: object
        "401":
          description: Unauthorized
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  type: string
              type: object
      summary: Authentication
  /signup:
    post:
      consumes:
      - application/json
      description: sign up on service with email and password
      parameters:
      - description: courier info
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/dto.UserDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.User'
        "400":
          description: Bad Request
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  type: string
              type: object
        "401":
          description: Unauthorized
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  type: string
              type: object
      summary: SignUp
schemes:
- http
swagger: "2.0"
