basePath: /
definitions:
  dto.Destination:
    properties:
      destination:
        type: string
    type: object
  entities.Delivery:
    properties:
      courier_id:
        type: integer
      createdAt:
        type: string
      destination:
        type: string
      id:
        type: integer
      recipient_id:
        type: integer
      status:
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:8081
info:
  contact:
    email: zhanbolat.nurutdin@gmail.com
    name: Zhanbolat
  title: Parcel Delivery Service
  version: "1.0"
paths:
  /deliveries:
    get:
      description: |-
        Fetch all deliveries. Only admin have permission to see all.
        If endpoint called with courier, only assigned deliveries returned
      parameters:
      - description: Authentication header. Usage 'Bearer {token}'
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/entities.Delivery'
              type: array
            type: array
        "400":
          description: Bad Request
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  type: string
              type: object
        "401":
          description: Unauthorized
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  type: string
              type: object
        "403":
          description: Forbidden
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  type: string
              type: object
      summary: fetch all deliveries
    post:
      consumes:
      - application/json
      description: create delivery order with required destination. Only user have
        permission.
      parameters:
      - description: Authentication header. Usage 'Bearer {token}'
        in: header
        name: Authorization
        required: true
        type: string
      - description: destination info
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/dto.Destination'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Delivery'
        "400":
          description: Bad Request
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  type: string
              type: object
        "401":
          description: Unauthorized
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  type: string
              type: object
        "403":
          description: Forbidden
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  type: string
              type: object
      summary: create delivery order
  /deliveries/{id}:
    get:
      description: |-
        Get one delivery. Only admin have permission to see all.
        If endpoint called with courier, only assigned deliveries returned
      parameters:
      - description: Authentication header. Usage 'Bearer {token}'
        in: header
        name: Authorization
        required: true
        type: string
      - description: delivery id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Delivery'
            type: array
        "400":
          description: Bad Request
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  type: string
              type: object
        "401":
          description: Unauthorized
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  type: string
              type: object
        "403":
          description: Forbidden
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  type: string
              type: object
      summary: get one delivery
  /deliveries/{id}/complete:
    put:
      description: Complete delivery. Only assigned courier have permission.
      parameters:
      - description: Authentication header. Usage 'Bearer {token}'
        in: header
        name: Authorization
        required: true
        type: string
      - description: delivery id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Delivery'
        "400":
          description: Bad Request
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  type: string
              type: object
        "401":
          description: Unauthorized
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  type: string
              type: object
        "403":
          description: Forbidden
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  type: string
              type: object
      summary: complete delivery
  /deliveries/{id}/courier/{courierId}:
    post:
      description: assign to courier the delivery order. Only admin have permission.
      parameters:
      - description: Authentication header. Usage 'Bearer {token}'
        in: header
        name: Authorization
        required: true
        type: string
      - description: delivery id
        in: path
        name: id
        required: true
        type: integer
      - description: courier id
        in: path
        name: courierId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Delivery'
        "400":
          description: Bad Request
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  type: string
              type: object
        "401":
          description: Unauthorized
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  type: string
              type: object
        "403":
          description: Forbidden
          schema:
            allOf:
            - type: object
            - properties:
                error:
                  type: string
              type: object
      summary: assign to courier
schemes:
- http
swagger: "2.0"
